/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halamanutama;
 import java.awt.Component;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import transaksibeli.transaksibeli;
import transaksijual.transaksijual;
import barang.barang;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import login.LOGIN1;
import koneksi.koneksi;
import java.math.BigDecimal;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Date;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.table.TableColumn;
import koneksi.DatabaseManager;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author alvon
 */
public class halamanutama extends javax.swing.JFrame {

  
    /**
     * Creates new form halamanutama
     */
     public halamanutama() {
         initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        loadData(); 
        calculateTotals();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpemasukantrkbeli = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpemasukantrkjual = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textpengeluaran = new javax.swing.JTextField();
        hasillaba = new javax.swing.JTextField();
        jgaji = new javax.swing.JTextField();
        jpengeluaran = new javax.swing.JTextField();
        jpemasukan = new javax.swing.JTextField();
        jpembelian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        dasboard = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blok biru.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 410, 80));

        tblpemasukantrkbeli.setBackground(new java.awt.Color(51, 153, 255));
        tblpemasukantrkbeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode_pembelian", "Tanggal_pembelian", "Jumlah_pembelian", "total_harga", "No_Ktp_Supplier", "Id_Barang"
            }
        ));
        jScrollPane1.setViewportView(tblpemasukantrkbeli);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 590, 330));

        tblpemasukantrkjual.setBackground(new java.awt.Color(51, 153, 255));
        tblpemasukantrkjual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "kode_penjualan", "Tanggal_penjualan", "Harga_jasa", "Plat_Nomor"
            }
        ));
        jScrollPane2.setViewportView(tblpemasukantrkjual);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 590, 330));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -20, -1, -1));

        jLabel5.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Beranda");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Transaksi Beli");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, -1, -1));

        jLabel7.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Transaksi Jual");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Barang");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        textpengeluaran.setBackground(new java.awt.Color (0, 0, 0, 0));
        textpengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textpengeluaran.setBorder(null);
        textpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpengeluaranActionPerformed(evt);
            }
        });
        getContentPane().add(textpengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 700, 180, 40));

        hasillaba.setBackground(new java.awt.Color (0, 0, 0, 0));
        hasillaba.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        hasillaba.setBorder(null);
        hasillaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasillabaActionPerformed(evt);
            }
        });
        getContentPane().add(hasillaba, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, 180, 40));

        jgaji.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jgaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgajiActionPerformed(evt);
            }
        });
        getContentPane().add(jgaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 630, 260, -1));

        jpengeluaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jpengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 260, -1));

        jpemasukan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jpemasukan.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jpemasukan.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(jpemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, 260, -1));

        jpembelian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 590, 260, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fc dash ownerbuwetull.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 800));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 800));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 900));

        logout.setText("jButton5");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 20, 100, 80));

        jButton4.setText("barang");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 120, 100));

        dasboard.setText("dashbord");
        dasboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dasboardActionPerformed(evt);
            }
        });
        getContentPane().add(dasboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 100));

        jButton2.setText("trxj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 120, 100));

        jButton3.setText("trxb");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 130, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dasboard karyawan.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 170, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadData() {
        loadTransaksiBeli();
        loadTransaksiJual();
        loadgaji ();
    }
private void loadTransaksiBeli() {
    DefaultTableModel model = (DefaultTableModel) tblpemasukantrkbeli.getModel();
    model.setRowCount(0); // Clear existing rows

    String sql = "SELECT * FROM transaksi_beli";
    try (Connection conn = DatabaseManager.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            Object[] row = {
                rs.getString("kode_pembelian"),
                rs.getDate("tanggal_pembelian"),  // You can format this date if needed
                rs.getDouble("Jumlah_pembelian"),
                rs.getDouble("total_harga"),
                rs.getString("No_Ktp_supplier"),
                rs.getString("Id_Barang")
            };
            model.addRow(row);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}

private void loadTransaksiJual() {
    DefaultTableModel model = (DefaultTableModel) tblpemasukantrkjual.getModel();
    model.setRowCount(0); // Clear existing rows

    String sql = "SELECT * FROM transaksi_jual";
    try (Connection conn = DatabaseManager.getConnection();
         PreparedStatement stmt = conn.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            Object[] row = {
                rs.getString("kode_penjualan"),
                rs.getDate("tanggal_penjualan"),  
                rs.getDouble("harga_jasa"),
                rs.getString("Plat_Nomor"),
                rs.getString("No_Ktp")
            };
            model.addRow(row);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}

private void calculateTotals() {
    double totalPembelian = 0;
    double totalPenjualan = 0;
    double totalGaji = 0;

    // Calculate total for pembelian
    DefaultTableModel modelBeli = (DefaultTableModel) tblpemasukantrkbeli.getModel();
    for (int i = 0; i < modelBeli.getRowCount(); i++) {
        Object totalHargaObj = modelBeli.getValueAt(i, 3); // total_harga column
        if (totalHargaObj instanceof Number) {
            totalPembelian += ((Number) totalHargaObj).doubleValue();
        }
    }

    // Calculate total for penjualan
    DefaultTableModel modelJual = (DefaultTableModel) tblpemasukantrkjual.getModel();
    for (int i = 0; i < modelJual.getRowCount(); i++) {
        Object hargaJasaObj = modelJual.getValueAt(i, 2); // harga_jasa column
        if (hargaJasaObj instanceof Number) {
            totalPenjualan += ((Number) hargaJasaObj).doubleValue();
        }
    }

    // Get total gaji from jgaji TextField
    try {
        String gajiText = jgaji.getText().replace(",", ""); // Remove thousands separator if any
        totalGaji = Double.parseDouble(gajiText);
    } catch (NumberFormatException e) {
        totalGaji = 0;
        System.err.println("Error parsing gaji: " + e.getMessage());
    }

    // Calculate total pengeluaran (pembelian + gaji)
    double totalPengeluaran = totalPembelian + totalGaji;

    // Calculate total laba (pemasukan - pengeluaran)
    double totalLaba = totalPenjualan - totalPengeluaran;

    // Format numbers for display
    NumberFormat formatter = NumberFormat.getInstance(Locale.US);
    formatter.setMaximumFractionDigits(2);
    formatter.setMinimumFractionDigits(2);

    // Set values to text fields
    jpembelian.setText(formatter.format(totalPembelian));
    jpemasukan.setText(formatter.format(totalPenjualan));
    jpengeluaran.setText(formatter.format(totalPembelian)); // Set jpengeluaran to show pembelian total
    textpengeluaran.setText(formatter.format(totalPengeluaran));
    hasillaba.setText(formatter.format(totalLaba));

}
  private void loadgaji() {
    try (Connection conn = DatabaseManager.getConnection();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT SUM(Gaji) as total_gaji FROM karyawan")) {

        if (rs.next()) {
            double totalGaji = rs.getDouble("total_gaji");
            jgaji.setText(String.format(Locale.US, "%,.2f", totalGaji));
        } else {
            jgaji.setText("0.00");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error retrieving salary data: " + e.getMessage(), 
            "Database Error", 
            JOptionPane.ERROR_MESSAGE);
        jgaji.setText("Error");
        e.printStackTrace(); 
    }
}



    private void dasboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dasboardActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dasboardActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 transaksibeli b  = new transaksibeli();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       transaksijual j  = new transaksijual();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
barang b  = new barang();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);
            
    if (pilihan == JOptionPane.YES_OPTION) {
        // Tutup frame saat ini
        this.dispose();
        
        // Buat dan tampilkan frame LOGIN1
        LOGIN1 L = new LOGIN1();
        L.setVisible(true);
    }
    }//GEN-LAST:event_logoutActionPerformed

    private void textpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpengeluaranActionPerformed

    private void hasillabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasillabaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasillabaActionPerformed

    private void jgajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgajiActionPerformed

    }//GEN-LAST:event_jgajiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new halamanutama().setVisible(true);
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dasboard;
    private javax.swing.JTextField hasillaba;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jgaji;
    private javax.swing.JTextField jpemasukan;
    private javax.swing.JTextField jpembelian;
    private javax.swing.JTextField jpengeluaran;
    private javax.swing.JButton logout;
    private javax.swing.JTable tblpemasukantrkbeli;
    private javax.swing.JTable tblpemasukantrkjual;
    private javax.swing.JTextField textpengeluaran;
    // End of variables declaration//GEN-END:variables


}