/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;
import javax.swing.SwingUtilities;
 import javax.swing.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import koneksi.koneksi;
import halamanutama.halamanutama;
import halamanutama1.halamanutama1;




/**
 *
 * @author alvon
 */
public class LOGIN1 extends javax.swing.JFrame {
   private boolean isPasswordVisible = false;
    private ImageIcon eyeOpenIcon;
    private ImageIcon eyeClosedIcon;

    /**
     * Creates new form LOGIN1
     */
    public LOGIN1() {
         initIcons(); 
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnshow = new javax.swing.JButton();
        jtxtusername = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jtxtlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnshow.setBackground(new java.awt.Color (0, 0, 0, 0));
        btnshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/show.png"))); // NOI18N
        btnshow.setBorder(null);
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });
        getContentPane().add(btnshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 420, -1, 50));

        jtxtusername.setBackground(new java.awt.Color (0, 0, 0, 0));
        jtxtusername.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtusername.setBorder(null);
        jtxtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 510, 60));

        password.setBackground(new java.awt.Color (0, 0, 0, 0));
        password.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        password.setBorder(null);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 420, 440, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fc loginnnnn.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        jtxtlogin.setText("LOGIN");
        jtxtlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtloginActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 620, 170, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void initIcons() {
        eyeOpenIcon = loadIcon("/image/show.png");
        eyeClosedIcon = loadIcon("/image/hifde.png");
    }

    private ImageIcon loadIcon(String path) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Could not find image: " + path);
            return null;
        }
    } 
    private void jtxtloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtloginActionPerformed
    String username = jtxtusername.getText().trim();
    String passwordStr = new String(password.getPassword()).trim();
    if (username.isEmpty() || passwordStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Username dan Password tidak boleh kosong!", 
            "Login Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    try {
        Connection conn = koneksi.koneksiDB();
        String sql = "SELECT * FROM akun WHERE username = ? AND password = ?";
        
        try (PreparedStatement pst = conn.prepareStatement(sql)) {
            pst.setString(1, username);
            pst.setString(2, passwordStr);

            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    String posisi = rs.getString("posisi");
                    JOptionPane.showMessageDialog(this, 
                        "Berhasil login sebagai " + posisi, 
                        "Login Sukses", 
                        JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    switch (posisi.toLowerCase()) {
                        case "owner":
                            new halamanutama().setVisible(true);
                            break;
                        case "karyawan":
                            new halamanutama1().setVisible(true);
                            break;
                        default:
                            JOptionPane.showMessageDialog(this, 
                                "Posisi tidak dikenali.", 
                                "Error", 
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "Username atau password salah!", 
                        "Login Gagal", 
                        JOptionPane.ERROR_MESSAGE);
                    jtxtusername.setText("");
                    password.setText("");
                    jtxtusername.requestFocus();
                }
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error koneksi database: " + e.getMessage(), 
            "Database Error", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    
    }//GEN-LAST:event_jtxtloginActionPerformed

    private void jtxtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtusernameActionPerformed

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
    if (isPasswordVisible) {
            password.setEchoChar('*');
            btnshow.setIcon(eyeClosedIcon);
            isPasswordVisible = false;
        } else {
            password.setEchoChar((char) 0);
            btnshow.setIcon(eyeOpenIcon);
            isPasswordVisible = true;
        }
    
   
    }//GEN-LAST:event_btnshowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(LOGIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        SwingUtilities.invokeLater(() -> new LOGIN1().setVisible(true));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnshow;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jtxtlogin;
    private javax.swing.JTextField jtxtusername;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
