/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package barang;
import halamanutama.halamanutama;
import login.LOGIN1;
import transaksibeli.transaksibeli;
import transaksijual.transaksijual;
import koneksi.koneksi;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import koneksi.DatabaseManager;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author alvon
 */
public class barang extends javax.swing.JFrame {
    public barang() {
         initComponents();
            loadData(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SEARCH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        txtidbarang = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        jumlahbarang = new javax.swing.JTextField();
        hargabarang = new javax.swing.JTextField();
        totalharga = new javax.swing.JTextField();
        noktp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnTAMBAH = new javax.swing.JButton();
        btnEDIT = new javax.swing.JButton();
        btnjumlah = new javax.swing.JButton();
        HAPUS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blok biru.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 380, 90));

        jLabel5.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Transaksi Beli");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        jLabel6.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Beranda");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Barang");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Transaksi Jual");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        SEARCH.setBackground(new java.awt.Color (0, 0, 0, 0));
        SEARCH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SEARCH.setForeground(new java.awt.Color(255, 255, 255));
        SEARCH.setBorder(null);
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        getContentPane().add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, 270, 40));

        tabel_barang.setAutoCreateRowSorter(true);
        tabel_barang.setBackground(new java.awt.Color(51, 153, 255));
        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_Barang", "Nama_Barang", "Jumlah_Barang", "Harga_Barang", "Total_Harga", "No_Ktp"
            }
        ));
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_barang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 660, 460));
        getContentPane().add(txtidbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 310, -1));

        txtnamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamabarangActionPerformed(evt);
            }
        });
        getContentPane().add(txtnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 310, -1));
        getContentPane().add(jumlahbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 310, -1));
        getContentPane().add(hargabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 310, -1));

        totalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalhargaActionPerformed(evt);
            }
        });
        getContentPane().add(totalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 310, -1));
        getContentPane().add(noktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 610, 310, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fc barang owner real.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 90));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, 90));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 110, 110));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 110, 110));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 20, 110, 80));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, -1, -1));

        btnTAMBAH.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnTAMBAH.setText("TAMBAH");
        btnTAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTAMBAHActionPerformed(evt);
            }
        });
        getContentPane().add(btnTAMBAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 680, 140, 40));

        btnEDIT.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnEDIT.setText("EDIT");
        btnEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEDITActionPerformed(evt);
            }
        });
        getContentPane().add(btnEDIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 680, 130, 40));

        btnjumlah.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnjumlah.setText("Hitung");
        btnjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjumlahActionPerformed(evt);
            }
        });
        getContentPane().add(btnjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 160, 50));

        HAPUS.setFont(new java.awt.Font("ROG Fonts", 0, 14)); // NOI18N
        HAPUS.setText("Hapus");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });
        getContentPane().add(HAPUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 670, 180, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void initComponent() {
       jScrollPane1 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_barang.setAutoCreateRowSorter(true);
        tabel_barang.setBackground(new java.awt.Color(153, 153, 153));
        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id_Barang", "Nama_Barang", "Jumlah_Barang", "Harga_Barang", "Total_Harga", "No_Ktp"
            }
        ));
        jScrollPane1.setViewportView(tabel_barang);
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 217, 1080, 490));
}
    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tabel_barang.getModel();
        model.setRowCount(0);
        try {
            Connection conn = koneksi.koneksiDB();
            String sql = "SELECT * FROM barang";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                String idBarang = rs.getString("Id_Barang");
                String namaBarang = rs.getString("Nama_Barang");
                int jumlahBarang = rs.getInt("Jumlah_Barang");
                double hargaBarang = rs.getDouble("Harga_Barang");
                double totalHarga = rs.getDouble("Total_Harga");
                String noKtp = rs.getString("No_Ktp");
                
                model.addRow(new Object[]{idBarang, namaBarang, jumlahBarang, hargaBarang, totalHarga, noKtp});
            }           
            rs.close();
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            System.err.println("Terjadi kesalahan: ");
            System.err.println(e.getMessage());
        }
    }
    public static void kurangiJumlahBarang(int id_barang, int jumlah_barang) {
        String query = "UPDATE barang SET Jumlah_Barang = Jumlah_Barang - ? WHERE Id_Barang = ?";
        try {
            Connection conn = koneksi.koneksiDB();
            PreparedStatement statement = conn.prepareStatement(query);
            statement.setInt(1, jumlah_barang);
            statement.setInt(2, id_barang);
            statement.executeUpdate();
            conn.close();
        } catch (SQLException e) {
            System.err.println("Terjadi kesalahan: ");
            System.err.println(e.getMessage());
        }  
}
     private boolean validateInputFields() {
    if (txtidbarang.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID Barang tidak boleh kosong", "Validasi Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if (txtnamabarang.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama Barang tidak boleh kosong", "Validasi Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    try {
        int jumlah = Integer.parseInt(jumlahbarang.getText());
        if (jumlah <= 0) {
            JOptionPane.showMessageDialog(this, "Jumlah Barang harus lebih dari 0", "Validasi Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah Barang harus angka", "Validasi Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    try {
        double harga = Double.parseDouble(hargabarang.getText());
        if (harga <= 0) {
            JOptionPane.showMessageDialog(this, "Harga Barang harus lebih dari 0", "Validasi Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harga Barang harus angka", "Validasi Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    if (noktp.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No KTP tidak boleh kosong", "Validasi Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
}
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         halamanutama hal = new halamanutama();
        hal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         barang b  = new barang();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        transaksijual j  = new transaksijual();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        transaksibeli b  = new transaksibeli();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       int pilihan = JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);
            
    if (pilihan == JOptionPane.YES_OPTION) {
        // Tutup frame saat ini
        this.dispose();
        
        // Buat dan tampilkan frame LOGIN1
        LOGIN1 L = new LOGIN1();
        L.setVisible(true);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
 int row = tabel_barang.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Silahkan pilih data yang akan dihapus",
            "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String idBarang = tabel_barang.getValueAt(row, 0).toString();
    int confirm = JOptionPane.showConfirmDialog(this,
        "Apakah anda yakin ingin menghapus barang dengan ID " + idBarang + "?",
        "Konfirmasi Hapus",
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try (Connection conn = koneksi.koneksiDB();
            PreparedStatement stmt = conn.prepareStatement(
                "DELETE FROM barang WHERE Id_Barang = ?")) {

            stmt.setString(1, idBarang); 

            int result = stmt.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                    "Data berhasil dihapus!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                loadData(); 
            } else {
                JOptionPane.showMessageDialog(this,
                    "Gagal menghapus data",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error menghapus data: " + e.getMessage(),
                "Database Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_HAPUSActionPerformed

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
       int row = tabel_barang.getSelectedRow();
    if (row >= 0) {
        HAPUS.setEnabled(true);
        btnEDIT.setEnabled(true);
        txtidbarang.setText(tabel_barang.getValueAt(row, 0).toString());
        txtnamabarang.setText(tabel_barang.getValueAt(row, 1).toString());
        jumlahbarang.setText(tabel_barang.getValueAt(row, 2).toString());
        hargabarang.setText(tabel_barang.getValueAt(row, 3).toString());
        totalharga.setText(tabel_barang.getValueAt(row, 4).toString());
        noktp.setText(tabel_barang.getValueAt(row, 5).toString());
        if (evt.getClickCount() == 2) {
            JOptionPane.showMessageDialog(this, 
                "Anda dapat mengedit data. Ubah field yang diperlukan dan klik tombol EDIT.", 
                "Edit Mode", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        String searchKeyword = SEARCH.getText().trim();
        if (!searchKeyword.isEmpty()) {
            try (Connection conn = koneksi.koneksiDB()) {
                String sql = "SELECT * FROM barang WHERE Nama_Barang LIKE ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, "%" + searchKeyword + "%");

                ResultSet rs = stmt.executeQuery();
                DefaultTableModel model = (DefaultTableModel) tabel_barang.getModel();
                model.setRowCount(0);

                while (rs.next()) {
                    String idBarang = rs.getString("Id_Barang");
                    String namaBarang = rs.getString("Nama_Barang");
                    int jumlahBarang = rs.getInt("Jumlah_Barang");
                    double hargaBarang = rs.getDouble("Harga_Barang");
                    double totalHarga = rs.getDouble("Total_Harga");
                    String noKtp = rs.getString("No_Ktp");
                    model.addRow(new Object[]{idBarang, namaBarang, jumlahBarang, hargaBarang, totalHarga, noKtp});
                }

                if (model.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan", "Pencarian Kosong", JOptionPane.INFORMATION_MESSAGE);
                }
                rs.close();
                stmt.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error during search: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Masukkan nama barang untuk pencarian!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_SEARCHActionPerformed

    private void btnEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEDITActionPerformed
       if (validateInputFields()) {
        try {
            Connection conn = koneksi.koneksiDB();
            String sql = "UPDATE barang SET Nama_Barang=?, Jumlah_Barang=?, Harga_Barang=?, Total_Harga=?, No_Ktp=? WHERE Id_Barang=?";
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, txtnamabarang.getText());
            stmt.setInt(2, Integer.parseInt(jumlahbarang.getText()));
            stmt.setDouble(3, Double.parseDouble(hargabarang.getText()));
            stmt.setDouble(4, Double.parseDouble(totalharga.getText()));
            stmt.setString(5, noktp.getText());
            stmt.setString(6, txtidbarang.getText());

            int result = stmt.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadData(); 
                clearInputFields(); 
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data", "Error", JOptionPane.ERROR_MESSAGE);
            }
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk Jumlah, Harga, dan Total Harga", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    }//GEN-LAST:event_btnEDITActionPerformed

    private void btnTAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTAMBAHActionPerformed
        if (validateInputFields()) {
        try {
            Connection conn = koneksi.koneksiDB();
            String sql = "INSERT INTO barang (Id_Barang, Nama_Barang, Jumlah_Barang, Harga_Barang, Total_Harga, No_Ktp) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, txtidbarang.getText());
            stmt.setString(2, txtnamabarang.getText());
            stmt.setInt(3, Integer.parseInt(jumlahbarang.getText()));
            stmt.setDouble(4, Double.parseDouble(hargabarang.getText()));
            stmt.setDouble(5, Double.parseDouble(totalharga.getText()));
            stmt.setString(6, noktp.getText());
            int result = stmt.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadData(); 
                clearInputFields(); 
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan data", "Error", JOptionPane.ERROR_MESSAGE);
            }
            stmt.close();
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid untuk Jumlah, Harga, dan Total Harga", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }
private void clearInputFields() {
    txtidbarang.setText("");
    txtnamabarang.setText("");
    jumlahbarang.setText("");
    hargabarang.setText("");
    totalharga.setText("");
    noktp.setText("");

    }//GEN-LAST:event_btnTAMBAHActionPerformed

    private void txtnamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamabarangActionPerformed

    private void totalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalhargaActionPerformed


    }//GEN-LAST:event_totalhargaActionPerformed

    private void btnjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjumlahActionPerformed
                                        
    try {
        double harga = Double.parseDouble(hargabarang.getText());
        int jumlah = Integer.parseInt(jumlahbarang.getText());
        double total = harga * jumlah;
        totalharga.setText(String.format("%.2f", total));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Masukkan angka yang valid untuk Harga Barang dan Jumlah Barang", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnjumlahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> new barang().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HAPUS;
    private javax.swing.JTextField SEARCH;
    private javax.swing.JButton btnEDIT;
    private javax.swing.JButton btnTAMBAH;
    private javax.swing.JButton btnjumlah;
    private javax.swing.JTextField hargabarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahbarang;
    private javax.swing.JTextField noktp;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTextField totalharga;
    private javax.swing.JTextField txtidbarang;
    private javax.swing.JTextField txtnamabarang;
    // End of variables declaration//GEN-END:variables
}
