/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halamanutama1;

/**
 *
 * @author alvon
 */
import halamanutama1.halamanutama1;
import trjual_karyawan.transaksijual_karyawan;
import Barang_karyawan.barang_karyawan;
import login.LOGIN1;
import javax.swing.*;

public class halamanutama1 extends javax.swing.JFrame {

    /**
     * Creates new form halamanutama1
     */
    public halamanutama1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        halkaryawan = new javax.swing.JButton();
        btnbrgkaryawan = new javax.swing.JButton();
        btntjkaryawan = new javax.swing.JButton();
        BTNLOGOUT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 410, 80));

        jLabel8.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel8.setText("Beranda");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel7.setText(" Barang");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 70, -1));

        jLabel6.setFont(new java.awt.Font("STKaiti", 1, 14)); // NOI18N
        jLabel6.setText("Transaksi Jual");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dasboard karyawan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 900));

        halkaryawan.setText("jButton1");
        halkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halkaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(halkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, 120));

        btnbrgkaryawan.setText("jButton2");
        btnbrgkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrgkaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(btnbrgkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, 110));

        btntjkaryawan.setText("jButton3");
        btntjkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntjkaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(btntjkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 130, 100));

        BTNLOGOUT.setText("jButton3");
        BTNLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(BTNLOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 10, 130, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void halkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halkaryawanActionPerformed
       halamanutama1 hal1 = new halamanutama1();
        hal1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_halkaryawanActionPerformed

    private void btnbrgkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrgkaryawanActionPerformed
        barang_karyawan b1  = new barang_karyawan();
        b1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbrgkaryawanActionPerformed

    private void btntjkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntjkaryawanActionPerformed
        transaksijual_karyawan j1  = new transaksijual_karyawan();
        j1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btntjkaryawanActionPerformed

    private void BTNLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLOGOUTActionPerformed
         int pilihan = JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);
            
    if (pilihan == JOptionPane.YES_OPTION) {
        // Tutup frame saat ini
        this.dispose();
        
        // Buat dan tampilkan frame LOGIN1
        LOGIN1 loginFrame = new LOGIN1();
        loginFrame.setVisible(true);
    }

    }//GEN-LAST:event_BTNLOGOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanutama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanutama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanutama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanutama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanutama1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNLOGOUT;
    private javax.swing.JButton btnbrgkaryawan;
    private javax.swing.JButton btntjkaryawan;
    private javax.swing.JButton halkaryawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
